mostaza_landing/urls.py
from django.conf.urls import url
from django.contrib import admin
from curso.views import * # estoy importando todo lo que hay en el archivo views de la carpeta curso

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^curso_analytics$',landing_analytics, name='landing_analytics'),
    url(r'^formulario/$',formulario, name='form'),# aca estoy diciendo que en esa url renderice la funcion home de curso.views
    url(r'^formulario/thankyou/$',thankyou, name='thankyou')
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

curso/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Prospecto(models.Model):
	nombre = models.CharField(max_length=120,  blank=False, null=True)#blank=False hace obligatorio el campo
	#apellido = models.CharField(max_length=120, blank=False, null=True)
	email = models.EmailField(blank=False)
	celular = models.CharField(max_length=120, blank=False)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	profesion = models.CharField(max_length=120, null=True, blank=True)
	state = models.CharField(max_length=120, null=True, blank=True)
	source = models.CharField(max_length=200, blank=True, null=True)
	medium = models.CharField(max_length=200, blank=True, null=True)
	campaign = models.CharField(max_length=200, blank=True, null=True)
	content = models.CharField(max_length=200, blank=True, null=True)
	latitude = models.CharField(max_length=200, blank=True, null=True)
	longitude = models.CharField(max_length=200, blank=True, null=True)

	def __str__(self):
		return self.email

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

curso/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
#Para renderizar los HTMLs que las vistas aca manejan.
from django.shortcuts import render
#Para importar como tal el formulario
from .form import *
#Para importar la funcionalidades de correos
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
#para validar el formulario
from django import forms
#Para traer los templates de los correos
from django.template.loader import render_to_string
#Para acceder a la URL de los documentos adjuntos
import urllib2
#Para redirigir despues a la pagina de agradecimiento.
from django.http import HttpResponseRedirect#Para redirigir despues a la pagina de agradecimiento.

# Create your views here.
def  landing_analytics(request):#Funcion para decir que renderice un html
	return render(request, "index.html", {})

def formulario(request): # Funcion para que renderice otro html
	#Estoy llamando el formulario que cree en forms.py y que ya tiene vinculado el modelo
	formulario_prospecto = ProspectoForm(
    	request.POST or None,
    	initial={#Con los initial estoy capturando los parametros de la URL
    		"source": request.GET.get("utm_source"),#capturando el parametro utm_source y guardandolo el el campo del formulario "source"
    		"medium": request.GET.get("utm_medium"),#capturando el parametro utm_medium y guardandolo el el campo del formulario "medium"
    		"campaign": request.GET.get("utm_campaign"),#capturando el parametro utm_campaign y guardandolo el el campo del formulario "campaign"
    		"content": request.GET.get("utm_content"),#capturando el parametro utm_content y guardandolo el el campo del formulario "content"
		}
	)
	#Un if condicional para validar si el formulario se diligencio
	if formulario_prospecto.is_valid():
		#Si el formulario se diligencio, lo guardo con el metodo .save()
		instance = formulario_prospecto.save()
		print "instance ={!r}".format(instance)
		#Capturo el correo que se metio en el formulario, usando un metodo que hice en la clase de forms.py
		email_prospecto = formulario_prospecto.clean_email()
		#Capturo el nombre que se metio en el formulario, usando un metodo que hice en la clase de forms.py
		nombre = formulario_prospecto.name_register()
		#Capturo el celular que se metio en el formulario, usando un metodo que hice en la clase de forms.py
		celular = formulario_prospecto.clean_celular()
		
		#ENVIO DEL CORREO 1 - CLIENTE
		#ELEMENTOS DEL CORREO 1
		#asunto:
		subject1= "Ya estas mas cerca de ser un experto en Google Analytics"
		#remitente:
		from_email1 = "cursos@mostaza.com.co"
		#destinatario, En este caso es el correo que capture en el formulario
		to_email1 = [email_prospecto]

		#TEMPLATES DEL CORREO
		#template como archivo txt con su contexto
		plantext1=render_to_string("mail-cliente.txt", {"nombre":nombre})
		#template como html con su contexto
		html1 = render_to_string("mail-cliente.html", {"nombre":nombre})

		#Clase para montar el objeto Correo
		email1 = EmailMultiAlternatives(subject1, plantext1,from_email1,to_email1)
		#hago que el Objeto correo que cree se envie en HTML
		email1.attach_alternative(html1,"text/html")

		#PDF ADJUNTO
		#Acceder a la URL donde esta el documento
		response = urllib2.urlopen("https://s3-us-west-1.amazonaws.com/mostazalanding/plan_estudios_curso_analytics.pdf")
		#Adjuntar el documento al correo
		email1.attach('plan_estudios_analytics.pdf', response.read(), mimetype="application/pdf")
		
		#ENVIO DEL CORREO 1
		#Metodo para enviar el primer correo
		email1.send()

		#ENVIO DEL CORREO 2 - EQUIPO COMERCIAL
		#ELEMENTOS DEL CORREO 2
		#Asunto:
		subject2="Hay un nuevo interesado en el curso de Google Analytics"
		#Remitente:
		from_email2="cursos@mostaza.com.co"
		#Destinatario:
		to_email2 = ["cursos@mostaza.com.co","mperalta@mostaza.com.co"]

		#TEMPLATES DEL CORREO 2
		#Template como archivo txt con sus contextos
		plantext2=render_to_string("mail-equipo.txt", {"nombre": nombre, "correo": email_prospecto, "celular":celular})
		html2 = render_to_string("mail-equipo.html", {"nombre": nombre, "correo": email_prospecto, "celular":celular})

		#Clase para montar el objeto de correo
		email2 = EmailMultiAlternatives(subject2,plantext2,from_email2,to_email2)
		#Hago que el objeto correo que cree se envio en HTML
		email2.attach_alternative(html2,"text/html")

		#ENVIO DEL CORREO 2
		#Metodo para enviar el segundo correo
		email2.send()

		#Aca estoy redirigiendo a la pagina de agradecimiento por que en el form del html redirijo a mi mismo para hacer el envio de los correos y el store de los datos
		return HttpResponseRedirect("/formulario/thankyou/")

	#Creo un diccionario que funcionara como contexto.
	context = {"form":formulario_prospecto}
	
	return render(request, "form.html",context)#Renderizo el HTML y el contexto definido.

def thankyou(request):
	return render(request, "thankyou.html", {})

templates/form.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
        <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Curso Google Analytics Bogota - Mostaza Studio</title>
    <link rel="stylesheet" href="https://s3-us-west-1.amazonaws.com/mostazalanding/css/foundation.css">
    <link rel="stylesheet" href="https://s3-us-west-1.amazonaws.com/mostazalanding/css/app.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,600" rel="stylesheet">
    <script src="https://use.fontawesome.com/48cf332b07.js"></script>
    <style type="text/css">
      .loader {
    border: 4px solid #f3f3f3; /* Light grey */
    border-top: 4px solid #FDB515; /* Blue */
    border-radius: 50%;
    width: 40px;
    height: 40px;
    animation: spin 2s linear infinite;
}
    .hidden_content{
      display:none;
    }
@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}

.jQuery-plainOverlay-progress {
  border-color: #FDB515 !important;
}

.jQuery-plainOverlay-progress-legacy div {
  background-color: #CDCDCD !important;
}
    </style>
  </head>
  <body id="body_formulario">
    <div class="row expanded header_form">
      <div class="row titulos">
      <img src="https://s3-us-west-1.amazonaws.com/mostazalanding/css/img/logo_mostaza.png" class="float-center logo_form">
        <div class="column small-centered large-centered medium-centered small-12 memium-10 large-10">
          <h1 class="text-center titulo_principal" id="titulo_form">¡Domina Google Analytics hoy!</h1>
          <h3 class="text-center subtitulo">Regalanos tus datos y recibiras el plan de estudios, mas informacion<br>sobre nuestro curso y como acceder a el.</h3>
        </div>
      </div>
      <div class="row form">
      <form method="POST" action="/formulario/" id="register_form">{%csrf_token%}
        <div class="column small-centered large-centered medium-centered large-4 small-10 medium-6">
          <!--<input type="text" name="" placeholder="Nombre">
          <input type="text" name="" placeholder="Celular">
          <input type="email" name="" placeholder="Correo Electronico">-->
          {{form}}
          <input type="submit" name="" class="button warning expanded" value="DESCARGAR PLAN DE ESTUDIOS" id="form_cta">
        </div>
        
      </form>
      </div>
      <div class=" hidden_content row loader column small-centered medium-centered large-centered small-10 medium-10 large-10" id="loader">
      </div>
      <div class="row">
        <div class="column small-centered medium-centered large-centered small-10 medium-10 large-10">
          <p class="text-center texto-imagen" id="texto_form">Recibiras un correo electronico con el Plan de Estudios del Curso de Google analytics<br>Un miembro de Mostaza Studio te contactara en menos de 24 horas para solucionar<br>todas tus dudas, preguntas e inquietudes</p>.
        </div>
      </div>
    </div>

    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/jquery.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/what-input.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/foundation.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/app.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/overlay/jquery.plainoverlay.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function() {
        function getLocation() {
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
          } else {
            console.log("Geolocation is not supported by this browser.");
          }
        }
        function showPosition(position) {
          $("#id_latitude").val(position.coords.latitude);
          $("#id_longitude").val(position.coords.longitude);
        }
        getLocation();
        /*$("#form_cta").click(function(){
            $("#loader").append("<div class='loader column small-centered medium-centered large-centered small-10 medium-10 large-10'></div>");
          });*/
          $("#register_form").on("submit", function() {
            $("body").plainOverlay("show", {
              progress: function() {
                var message = "Enviando el plan de estudios";
                var icon = "<i class='fa fa-spinner fa-spin fa-5x'></i>";
                var content = "<div class='text-center'>" + icon + "<br>" + message + "</div>";
                return $(content);
              }
            });
          });  
        });
    </script>
  </body>
</html>

templates/formulario.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carogobot Registration</title>
    <link rel="stylesheet" href="https://s3-us-west-1.amazonaws.com/mostazalanding/css/foundation.css">
    <link rel="stylesheet" href="https://s3-us-west-1.amazonaws.com/mostazalanding/css/app.css">
  </head>
  <body>
    <div class="row column expanded contenedor">
      <div class="row logo">
        <div class="column small-centered medium-centered large-centered">
          <img src="img/logo.png" class="float-center">
        </div>
      </div>
      <div class="row titulos_formulario">
        <div class="column small-centered medium-centered large-centered titulo">
          <h1 class="text-center titulo_principal">The best way to connect carriers and shippers</h1>
          <h3 class="text-center subtitulo">Shippers nationwide are operating with our 3TN. To begin your registration process fill in the<br>information required below. Get clients every day!</h3>          
        </div>
      </div>
      <div class="row formulario">
          <form method="POST" action="">{%csrf_token%}
              <div class="column small-centered medium-centered large-centered large-4 medium-6 small-10">
                <!--<input type="text" name="" placeholder="Nombres">
                <input type="text" name="" placeholder="Apellidos">
                <input type="text" name="" placeholder="Celular">
                <input type="email" name="" placeholder="Correo Electronico">-->
                {{form}}
                <input type="submit" name="" class="button warning expanded" value="APRENDER GOOGLE ANALYTICS">
              </div>
          </form>
      </div>
      <div class="row">
        <div class="column small-centered medium-centered large-centered">
          <p class="text-center textos_w">A member from our CargoBot team will contact you within 24 hours.</p>
          <p class="text-center textos_w">Visit us at <a href="#">cargobot.io</a></p>
          <p class="text-center textos_w copyright">Copyright Cargobot. All rights reserverd.</p>
        </div>
      </div>
    </div>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/jquery.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/what-input.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/foundation.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/app.js"></script>
  </body>
</html>

templates/landing_analytics.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carogobot for Carriers</title>
    <link rel="stylesheet" href="https://s3-us-west-1.amazonaws.com/mostazalanding/css/foundation.css">
    <link rel="stylesheet" href="https://s3-us-west-1.amazonaws.com/mostazalanding/css/app.css">
  </head>
  <body>
    <div class="row expanded header column">
      <div class="row">
        <div class="column">  
          <img src="img/cargobot.png" class="float-center logo">
         </div>
      </div>
      <div class="row">
        <div class="column small-centered medium-centered large-centered">
          <h1 class="titulo_principal text-center">Take part of the 3TN.<br>Take the power of negotation</h1>
        </div>
      </div>
      <div class="row">
        <div class="column small-centered medium-centered large-centered">
          <h3 class="subtitulo text-center">With CargoBot, you take part of a transparent truck transportation netwotk (3TN)<br>that believes the poweer of negotation should be in the carrier's hands.</h3>
        </div>
      </div>
      <div class="row">
        <div class="button-group small-centered medium-centered large-centered large-6 medium-6 stacked-for-small stacked-for-medium">
          <a href="/formulario" class="button botones">REGISTER FOR FREE NOW</a>
          <a href="" class="button botones">WATCH VIDEO</a>
        </div>
      </div>
    </div>
    <div class="row expanded bloque_2 column">
      <div class="row">
        <div class="column small-centered medium-centered large-centered">
          <h2 class="declaraciones text-center">No Intermediaries!<br>Negotiate directly with shippers!</h2>
        </div>
        <div class="column small-centered medium-centered large-centered">
          <p class="decla_sub_w text-center">CargoBot is a channel between you and your potential clients.<br>They post their shiptment needs and you decide if it's the right load for you</p>
        </div>  
      </div>
      <div class="row small-up-1 medium-up-1 large-up-3 grilla">
        <div class="column column-block ">
          <img src="img/more_loads.png" class="float-center">
          <br>
          <p class="textos_w text-center">MORE LOADS</p>
          <p class="textos_w text-center">Receive new loads instantly</p>
        </div>  
        <div class="column column-block">  
          <img src="img/bid_negotiate.png" class="float-center">
          <br>
          <p class="textos_w text-center">BID AND NEGOTIATE</p>
          <p class="textos_w text-center">Negotiate directly with shipper. See the lowest bid being offered</p>
        </div>  
        <div class="column column-block">  
          <img src="img/close_deal.png" class="float-center">
          <br>
          <p class="textos_w text-center">CLOSE THE DEAL</p>
          <p class="textos_w text-center">Make more money on your own terms.</p>
        </div>
      </div>
    </div>
        <div class="row expanded bloque_3 column">
      <div class="row">
        <div class="column small-centered medium-centered large-centered">
          <h2 class="declaraciones text-center" id="decla_3">Same process, but better!</h2>
        </div>
        <div class="column small-centered medium-centered large-centered">
          <p class="decla_sub_b text-center">Connecting you to a network of shippers through technology, backed by a committed team.</p>
        </div>  
      </div>
      <div class="row small-up-1 medium-up-1 large-up-3 grilla">
        <div class="column column-block ">
          <img src="img/guaranteed_payment.png" class="float-center">
          <br>
          <p class="textos text-center">GUARANTEED PAYMENT</p>
          <p class="textos text-center">Choose when you want to get paid; CargBot pays you out.</p>
        </div>  
        <div class="column column-block">  
          <img src="img/no_paperwork.png" class="float-center">
          <br>
          <p class="textos text-center">NO MORE PAPERWORK</p>
          <p class="textos text-center">All peperwork is now stored electronically ( Rate confirmation, BOL, POD, Invoice)</p>
        </div>  
        <div class="column column-block">  
          <img src="img/transparency.png" class="float-center">
          <br>
          <p class="textos text-center">TRANSPARENCY</p>
          <p class="textos text-center">CargoBot has no hiddon agendas, know your profit before moving a load</p>
        </div>
      </div>
    </div>
    <div class=" row expanded bloque_4">
      <div class="row">
        <div class="column small-centered medium-centered large-centered ">
          <h2 class="declaraciones text-center cierre">Be one of the first 100<br>carriers to access.</h2>
        </div>
        <div class="column small-centered medium-centered large-centered text-center">
          <a href="" class="button boton_cierre">REQUEST PRIME ACCESS</a>
          <br>
          <p class="textos_w">Are you a shipper? <a href="">Click here</a></p>
          </div>
          <div class="row">
            <div class="column large-4 small-12 medium-2 small-centered medium-centered large-centered">
              <div class="row small-up-3 medium-up-3 large-up-3 grilla_social gutter-small">
                <div class="column column-block ">
                  <a href=""><img src="img/linkedin.png" class="float-center"></a>
                </div>
                <div class="column column-block ">
                  <a href=""><img src="img/facebook.png" class="float-center"></a>
                </div>
                <div class="column column-block ">
                  <a href=""><img src="img/instagram.png" class="float-center"></a>
                </div>
              </div>
            </div>
            <p class="text-center textos_w">Copiright Cargobot. All rights reserverd.</p>
          </div>
        </div>
      </div>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/jquery.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/what-input.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/foundation.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/app.js"></script>
  </body>
</html>

templates/mail-cliente.html
<h1>Hola {{nombre}}</h1>
<p>Bienvenido a nuestro curso de analytics</p>

templates/mail-equipo.html
<h1>Hola</h1>
<p>Hay un nuevo registro de una persona interesada en el curso de google analytics:</p>
<p>Nombre: {{nombre}}</p>
<p>Correo: {{correo}}</p>
<p>Celular:{{celular}}</p>
<p>Llamalo en cuento puedas</p>

templates/thankyou.html
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Curso Google Analytics Bogota - Mostaza Studio</title>
    <link rel="stylesheet" href="https://s3-us-west-1.amazonaws.com/mostazalanding/css/foundation.css">
    <link rel="stylesheet" href="https://s3-us-west-1.amazonaws.com/mostazalanding/css/app.css">
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,600" rel="stylesheet">
    <script src="https://use.fontawesome.com/48cf332b07.js"></script>
  </head>
  <body id="body_formulario">
    <div class="row expanded header_form">
      <div class="row titulos">
      <img src="https://s3-us-west-1.amazonaws.com/mostazalanding/css/img/logo_mostaza.png" class="float-center logo_form">
        <div class="column small-centered large-centered medium-centered small-12 memium-10 large-10">
          <h1 class="text-center titulo_principal" id="titulo_form">¡Ya estamos enviando el plan de estudios a tu correo!</h1>
          <h3 class="text-center subtitulo"></h3>
        </div>
      </div>
      <div class="row">
        <div class="column small-centered medium-centered large-centered small-10 medium-10 large-10">
          <p class="text-center texto-imagen" id="texto_form">En dado caso que no hallas recibido el correo con el plan de estudios, puedes escribirnos a cursos@mostaza.com.co y un integrante del equipo te hara llegar toda la informacion directamente</p>.
        </div>
      </div>
    </div>

    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/jquery.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/what-input.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/vendor/foundation.js"></script>
    <script src="https://s3-us-west-1.amazonaws.com/mostazalanding/js/app.js"></script>
  </body>
</html>